# Generated by Django 5.2.8 on 2025-12-02 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("permissions", "0001_initial"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="roles",
            field=models.ManyToManyField(
                blank=True,
                related_name="users",
                to="permissions.role",
                verbose_name="Роли",
            ),
        ),
    ]
